name: CI

on: [push]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        ruby_version:
          - '3.0'
          - 2.7
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake spec

